# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sds.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sds.proto',
  package='tv.twitch.fuel.sds',
  syntax='proto3',
  serialized_pb=_b('\n\tsds.proto\x12\x12tv.twitch.fuel.sds\"R\n\x13\x43ompressionSettings\x12;\n\talgorithm\x18\x01 \x01(\x0e\x32(.tv.twitch.fuel.sds.CompressionAlgorithm\"!\n\x03\x44ir\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\r\"\x89\x01\n\x04\x46ile\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\r\x12\x0c\n\x04size\x18\x03 \x01(\x03\x12\x0f\n\x07\x63reated\x18\x04 \x01(\t\x12&\n\x04hash\x18\x05 \x01(\x0b\x32\x18.tv.twitch.fuel.sds.Hash\x12\x0e\n\x06hidden\x18\x06 \x01(\x08\x12\x0e\n\x06system\x18\x07 \x01(\x08\"K\n\x04Hash\x12\x34\n\talgorithm\x18\x01 \x01(\x0e\x32!.tv.twitch.fuel.sds.HashAlgorithm\x12\r\n\x05value\x18\x02 \x01(\x0c\"=\n\x08Manifest\x12\x31\n\x08packages\x18\x01 \x03(\x0b\x32\x1b.tv.twitch.fuel.sds.PackageB\x02\x10\x00\"\xa8\x01\n\x0eManifestHeader\x12<\n\x0b\x63ompression\x18\x01 \x01(\x0b\x32\'.tv.twitch.fuel.sds.CompressionSettings\x12&\n\x04hash\x18\x02 \x01(\x0b\x32\x18.tv.twitch.fuel.sds.Hash\x12\x30\n\tsignature\x18\x03 \x01(\x0b\x32\x1d.tv.twitch.fuel.sds.Signature\"o\n\x07Package\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x18.tv.twitch.fuel.sds.FileB\x02\x10\x00\x12)\n\x04\x64irs\x18\x03 \x03(\x0b\x32\x17.tv.twitch.fuel.sds.DirB\x02\x10\x00\"U\n\tSignature\x12\x39\n\talgorithm\x18\x01 \x01(\x0e\x32&.tv.twitch.fuel.sds.SignatureAlgorithm\x12\r\n\x05value\x18\x02 \x01(\x0c**\n\x14\x43ompressionAlgorithm\x12\x08\n\x04none\x10\x00\x12\x08\n\x04lzma\x10\x01*)\n\rHashAlgorithm\x12\n\n\x06sha256\x10\x00\x12\x0c\n\x08shake128\x10\x01*)\n\x12SignatureAlgorithm\x12\x13\n\x0fsha256_with_rsa\x10\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_COMPRESSIONALGORITHM = _descriptor.EnumDescriptor(
  name='CompressionAlgorithm',
  full_name='tv.twitch.fuel.sds.CompressionAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='none', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='lzma', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=803,
  serialized_end=845,
)
_sym_db.RegisterEnumDescriptor(_COMPRESSIONALGORITHM)

CompressionAlgorithm = enum_type_wrapper.EnumTypeWrapper(_COMPRESSIONALGORITHM)
_HASHALGORITHM = _descriptor.EnumDescriptor(
  name='HashAlgorithm',
  full_name='tv.twitch.fuel.sds.HashAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='sha256', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='shake128', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=847,
  serialized_end=888,
)
_sym_db.RegisterEnumDescriptor(_HASHALGORITHM)

HashAlgorithm = enum_type_wrapper.EnumTypeWrapper(_HASHALGORITHM)
_SIGNATUREALGORITHM = _descriptor.EnumDescriptor(
  name='SignatureAlgorithm',
  full_name='tv.twitch.fuel.sds.SignatureAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='sha256_with_rsa', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=890,
  serialized_end=931,
)
_sym_db.RegisterEnumDescriptor(_SIGNATUREALGORITHM)

SignatureAlgorithm = enum_type_wrapper.EnumTypeWrapper(_SIGNATUREALGORITHM)
none = 0
lzma = 1
sha256 = 0
shake128 = 1
sha256_with_rsa = 0



_COMPRESSIONSETTINGS = _descriptor.Descriptor(
  name='CompressionSettings',
  full_name='tv.twitch.fuel.sds.CompressionSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='tv.twitch.fuel.sds.CompressionSettings.algorithm', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=115,
)


_DIR = _descriptor.Descriptor(
  name='Dir',
  full_name='tv.twitch.fuel.sds.Dir',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='tv.twitch.fuel.sds.Dir.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='tv.twitch.fuel.sds.Dir.mode', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=150,
)


_FILE = _descriptor.Descriptor(
  name='File',
  full_name='tv.twitch.fuel.sds.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='tv.twitch.fuel.sds.File.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='tv.twitch.fuel.sds.File.mode', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='tv.twitch.fuel.sds.File.size', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created', full_name='tv.twitch.fuel.sds.File.created', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='tv.twitch.fuel.sds.File.hash', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hidden', full_name='tv.twitch.fuel.sds.File.hidden', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system', full_name='tv.twitch.fuel.sds.File.system', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=290,
)


_HASH = _descriptor.Descriptor(
  name='Hash',
  full_name='tv.twitch.fuel.sds.Hash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='tv.twitch.fuel.sds.Hash.algorithm', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='tv.twitch.fuel.sds.Hash.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=367,
)


_MANIFEST = _descriptor.Descriptor(
  name='Manifest',
  full_name='tv.twitch.fuel.sds.Manifest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packages', full_name='tv.twitch.fuel.sds.Manifest.packages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\000'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=430,
)


_MANIFESTHEADER = _descriptor.Descriptor(
  name='ManifestHeader',
  full_name='tv.twitch.fuel.sds.ManifestHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='compression', full_name='tv.twitch.fuel.sds.ManifestHeader.compression', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='tv.twitch.fuel.sds.ManifestHeader.hash', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='tv.twitch.fuel.sds.ManifestHeader.signature', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=601,
)


_PACKAGE = _descriptor.Descriptor(
  name='Package',
  full_name='tv.twitch.fuel.sds.Package',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tv.twitch.fuel.sds.Package.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='files', full_name='tv.twitch.fuel.sds.Package.files', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\000'))),
    _descriptor.FieldDescriptor(
      name='dirs', full_name='tv.twitch.fuel.sds.Package.dirs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\000'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=603,
  serialized_end=714,
)


_SIGNATURE = _descriptor.Descriptor(
  name='Signature',
  full_name='tv.twitch.fuel.sds.Signature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='tv.twitch.fuel.sds.Signature.algorithm', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='tv.twitch.fuel.sds.Signature.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=716,
  serialized_end=801,
)

_COMPRESSIONSETTINGS.fields_by_name['algorithm'].enum_type = _COMPRESSIONALGORITHM
_FILE.fields_by_name['hash'].message_type = _HASH
_HASH.fields_by_name['algorithm'].enum_type = _HASHALGORITHM
_MANIFEST.fields_by_name['packages'].message_type = _PACKAGE
_MANIFESTHEADER.fields_by_name['compression'].message_type = _COMPRESSIONSETTINGS
_MANIFESTHEADER.fields_by_name['hash'].message_type = _HASH
_MANIFESTHEADER.fields_by_name['signature'].message_type = _SIGNATURE
_PACKAGE.fields_by_name['files'].message_type = _FILE
_PACKAGE.fields_by_name['dirs'].message_type = _DIR
_SIGNATURE.fields_by_name['algorithm'].enum_type = _SIGNATUREALGORITHM
DESCRIPTOR.message_types_by_name['CompressionSettings'] = _COMPRESSIONSETTINGS
DESCRIPTOR.message_types_by_name['Dir'] = _DIR
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['Hash'] = _HASH
DESCRIPTOR.message_types_by_name['Manifest'] = _MANIFEST
DESCRIPTOR.message_types_by_name['ManifestHeader'] = _MANIFESTHEADER
DESCRIPTOR.message_types_by_name['Package'] = _PACKAGE
DESCRIPTOR.message_types_by_name['Signature'] = _SIGNATURE
DESCRIPTOR.enum_types_by_name['CompressionAlgorithm'] = _COMPRESSIONALGORITHM
DESCRIPTOR.enum_types_by_name['HashAlgorithm'] = _HASHALGORITHM
DESCRIPTOR.enum_types_by_name['SignatureAlgorithm'] = _SIGNATUREALGORITHM

CompressionSettings = _reflection.GeneratedProtocolMessageType('CompressionSettings', (_message.Message,), dict(
  DESCRIPTOR = _COMPRESSIONSETTINGS,
  __module__ = 'sds_pb2'
  # @@protoc_insertion_point(class_scope:tv.twitch.fuel.sds.CompressionSettings)
  ))
_sym_db.RegisterMessage(CompressionSettings)

Dir = _reflection.GeneratedProtocolMessageType('Dir', (_message.Message,), dict(
  DESCRIPTOR = _DIR,
  __module__ = 'sds_pb2'
  # @@protoc_insertion_point(class_scope:tv.twitch.fuel.sds.Dir)
  ))
_sym_db.RegisterMessage(Dir)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
  DESCRIPTOR = _FILE,
  __module__ = 'sds_pb2'
  # @@protoc_insertion_point(class_scope:tv.twitch.fuel.sds.File)
  ))
_sym_db.RegisterMessage(File)

Hash = _reflection.GeneratedProtocolMessageType('Hash', (_message.Message,), dict(
  DESCRIPTOR = _HASH,
  __module__ = 'sds_pb2'
  # @@protoc_insertion_point(class_scope:tv.twitch.fuel.sds.Hash)
  ))
_sym_db.RegisterMessage(Hash)

Manifest = _reflection.GeneratedProtocolMessageType('Manifest', (_message.Message,), dict(
  DESCRIPTOR = _MANIFEST,
  __module__ = 'sds_pb2'
  # @@protoc_insertion_point(class_scope:tv.twitch.fuel.sds.Manifest)
  ))
_sym_db.RegisterMessage(Manifest)

ManifestHeader = _reflection.GeneratedProtocolMessageType('ManifestHeader', (_message.Message,), dict(
  DESCRIPTOR = _MANIFESTHEADER,
  __module__ = 'sds_pb2'
  # @@protoc_insertion_point(class_scope:tv.twitch.fuel.sds.ManifestHeader)
  ))
_sym_db.RegisterMessage(ManifestHeader)

Package = _reflection.GeneratedProtocolMessageType('Package', (_message.Message,), dict(
  DESCRIPTOR = _PACKAGE,
  __module__ = 'sds_pb2'
  # @@protoc_insertion_point(class_scope:tv.twitch.fuel.sds.Package)
  ))
_sym_db.RegisterMessage(Package)

Signature = _reflection.GeneratedProtocolMessageType('Signature', (_message.Message,), dict(
  DESCRIPTOR = _SIGNATURE,
  __module__ = 'sds_pb2'
  # @@protoc_insertion_point(class_scope:tv.twitch.fuel.sds.Signature)
  ))
_sym_db.RegisterMessage(Signature)


_MANIFEST.fields_by_name['packages'].has_options = True
_MANIFEST.fields_by_name['packages']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\000'))
_PACKAGE.fields_by_name['files'].has_options = True
_PACKAGE.fields_by_name['files']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\000'))
_PACKAGE.fields_by_name['dirs'].has_options = True
_PACKAGE.fields_by_name['dirs']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\000'))
# @@protoc_insertion_point(module_scope)
